### ISSUE TITLE
Can't run all the version starting from 0.90 to 0.93

### ISSUE THREAD

**Issue by sharemashina** [ModernFlyouts-Community/ModernFlyouts#1145]
### ModernFlyouts Version

cant actually check but installation was 0.93

### Windows version

Windows 11 22H2

### OS build

22623.1028

### Platform

x64

### Area(s) with issue?

General, Installer

### Steps to reproduce

1. install ModernFlyouts from MS/Gh - nothing happens.
2. Reinstalling to other versions (0.90) nothing happens

When I install ModernFlyouts and start it, nothing happens. When I start it via admin, nothing happens too. I looked in the task manager and also nothing was happening with any versions

### ✔️ Expected Behavior

No response

### ❌ Actual Behavior

0.9.3 (Latest) and 0.90 both are unable to start. I saw solution from #1078 but it doesn't start up
My pc specs: 
CPU: i3 10100f 
RAM: 16 gb 
GPU: GTX 1050Ti

### Other Software

No response

### Additional Context

No response

**Comment by EudenDev** [comment]
Same here, but I unistalled the store version then installed the 0.9.0. It seems to work for now.

**Comment by sharemashina** [comment]
> Same here, but I unistalled the store version then installed the 0.9.0. It seems to work for now. Updating to the MS Store version breaks it :(
> 
> Windows 11 22H2
 
Still have dis problem(
I tried each of the possible versions but nothing helped(

**Comment by hdadhich01** [comment]
Would recommend [this workaround](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1161#issuecomment-1399208776) for now.

**Comment by sharemashina** [comment]
> Would recommend [this workaround](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1161#issuecomment-1399208776) for now.

dude cant helped fr

**Comment by faruq-q** [comment]
First, delete the version installed on your computer. then disable automatic updates from microsoft store. then download and install the version in [this link](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/download/v0.9.0/32669SamG.ModernFlyouts_0.9.0.0_neutral___pcy8vm99wrpcg.Msixbundle). It should work now.

![Screenshot_52](https://user-images.githubusercontent.com/76094369/215562392-ab2da121-77b1-4c8a-9edc-7122a4ac1595.png)
![Screenshot_53](https://user-images.githubusercontent.com/76094369/215562442-37ccacba-0265-4b5f-8202-2e0dd9d27e69.png)
![Screenshot_54](https://user-images.githubusercontent.com/76094369/215562469-bd04c544-a240-4597-aaa6-939a86a0f000.png)

**Comment by hdadhich01** [comment]
You can disable updates last, it's important to completely uninstall the existing app and then reinstall <=0.9.0.

**Comment by sharemashina** [comment]
I had problems disabling auto-update. I solved it but the problem remained the same
I don't know what to do anymore... I tried 0.9.0, 9.3, 8.5 versions....
i wanna drop it
Have some thouhts to go back to windows 10 just because of this..

**Comment by hdadhich01** [comment]
You may haven't uninstalled ModernFlyouts before individually installed and tested the executable versions. Also, if that doesn't work, try uninstalling then deleting its cache or backed up data. Other ways I can think of is just making sure you're up to date with the latest dist (21H2/22H2).

**Comment by sharemashina** [comment]
> 

It would be stupid to install the application without deleting its previous version.
Of course, I checke but it still didn't help
![image](https://user-images.githubusercontent.com/120036742/216337658-deefd6ed-8664-43fc-a357-2119f3592fc9.png)

**Comment by hdadhich01** [comment]
You could try resetting your Microsoft Store app, as it may be still updating the application right after installation in the background. Other solutions could be trying to find and delete any leftover folders/cache/data from ModernFlyouts in your system after an uninstall, since they may contain the expired certificate that every installs defaults to. Besides that, I'm not really sure of a solution besides testing on another device with the same configuration without the feature experience pack. The workaround seems to workaround in the tread above seems to work for others.

**Comment by manstheram** [comment]
Try v10 beta 3.
